### ISSUE TITLE
don't work

### ISSUE THREAD

**Issue by kev1nl1u** [andreaVMC/every-point-file-append-in-C#1]
bro i used it to every point file append in C but it brakes i want my money back refund now

**Comment by andreaVMC** [comment]
keep my program's name out of your mouth, it work perfectly.

**Comment by andreaVMC** [comment]
No refaund sorry i only can vive you the refaund of you vive me an 1000€ on
revolute, only for the commissions obviusly

Il lun 9 mag 2022, 20:00 Kevin ***@***.***> ha scritto:

**Comment by kev1nl1u** [comment]
every point file append in C doesn't work!!! customer support doesn't exit i give 2⭐/5 (⭐⭐/⭐⭐⭐⭐⭐) please refund and i give ⭐⭐⭐

**Comment by andreaVMC** [comment]
you're lying, no refunds for liars
